In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]

In [9]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size = 0.30, random_state = 0)

In [11]:
X_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'max_features':['sqrt','log2'],'n_estimators':[10,25,50,75,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 25, 50, 75, 100]},
             verbose=3)

In [14]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 75}:

In [15]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.062061,0.001474,0.008090,0.001297,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.839912,0.771521,0.796417,0.805713,0.761895,0.795092,0.027499,36
1,0.142362,0.016632,0.010409,0.001042,squared_error,sqrt,25,"{'criterion': 'squared_error', 'max_features':...",0.858934,0.792382,0.801148,0.818550,0.762662,0.806735,0.031762,27
2,0.217130,0.021288,0.013330,0.001412,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.858366,0.783228,0.807346,0.828951,0.765687,0.808716,0.032795,21
3,0.285514,0.011787,0.018379,0.002489,squared_error,sqrt,75,"{'criterion': 'squared_error', 'max_features':...",0.866007,0.799692,0.808312,0.826272,0.769733,0.814003,0.031787,1
4,0.398706,0.005457,0.019939,0.001162,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.865978,0.797366,0.808123,0.829198,0.766763,0.813486,0.033088,2
5,0.046265,0.007306,0.005987,0.000252,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.824343,0.762344,0.799276,0.811739,0.750993,0.789739,0.028369,39
6,0.095801,0.001003,0.008670,0.000326,squared_error,log2,25,"{'criterion': 'squared_error', 'max_features':...",0.856826,0.781264,0.799262,0.825379,0.767946,0.806135,0.031825,28
7,0.182924,0.003740,0.012703,0.001143,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.867325,0.781063,0.810030,0.821250,0.768810,0.809696,0.034485,18
8,0.270146,0.004470,0.015774,0.000534,squared_error,log2,75,"{'criterion': 'squared_error', 'max_features':...",0.866714,0.788329,0.802163,0.832423,0.770623,0.812050,0.034000,5
9,0.370447,0.008829,0.021190,0.001364,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856940,0.794534,0.799773,0.823719,0.758941,0.806781,0.032529,26
10,0.042571,0.001440,0.006815,0.001611,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.846023,0.782493,0.786184,0.788497,0.738566,0.788353,0.034187,40
11,0.104309,0.004813,0.010409,0.003088,friedman_mse,sqrt,25,"{'criterion': 'friedman_mse', 'max_features': ...",0.864931,0.782611,0.803051,0.822748,0.775667,0.809801,0.032115,17
12,0.199467,0.008683,0.012678,0.001440,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.868096,0.784538,0.804873,0.826753,0.772684,0.811389,0.033803,10
13,0.278098,0.002212,0.016768,0.001789,friedman_mse,sqrt,75,"{'criterion': 'friedman_mse', 'max_features': ...",0.863240,0.785491,0.810660,0.826760,0.766602,0.810551,0.033462,14
14,0.372567,0.006123,0.020940,0.001040,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.868112,0.793192,0.804966,0.824665,0.766215,0.811430,0.034079,9
15,0.042404,0.000932,0.006039,0.000338,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.852564,0.772919,0.803306,0.791947,0.759209,0.795989,0.032111,34
16,0.094408,0.002980,0.008575,0.000705,friedman_mse,log2,25,"{'criterion': 'friedman_mse', 'max_features': ...",0.853733,0.782811,0.802458,0.815290,0.768578,0.804574,0.029344,30
17,0.182653,0.003889,0.012177,0.000767,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.866183,0.787407,0.809811,0.822577,0.758532,0.808902,0.035967,20
18,0.271953,0.006790,0.016052,0.001266,friedman_mse,log2,75,"{'criterion': 'friedman_mse', 'max_features': ...",0.862293,0.789894,0.813395,0.825662,0.771683,0.812586,0.031082,4
19,0.360312,0.007793,0.019444,0.001646,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.862444,0.792971,0.805885,0.823517,0.765972,0.810158,0.032182,15
20,0.093493,0.003965,0.005756,0.000307,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.855048,0.768363,0.771655,0.822182,0.761403,0.795730,0.036675,35
21,0.229171,0.008719,0.009529,0.001677,absolute_error,sqrt,25,"{'criterion': 'absolute_error', 'max_features'...",0.846524,0.783211,0.802506,0.824429,0.763959,0.804126,0.029200,31
22,0.457224,0.013794,0.013306,0.003605,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.850131,0.782195,0.813447,0.817480,0.764351,0.805521,0.029783,29
23,0.679632,0.016192,0.015304,0.001137,absolute_error,sqrt,75,"{'criterion': 'absolute_error', 'max_features'...",0.853705,0.787235,0.811265,0.830917,0.773011,0.811227,0.029080,11
24,0.901888,0.011943,0.019837,0.001161,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.854149,0.786866,0.813850,0.828954,0.770239,0.810812,0.029786,12
25,0.095020,0.005124,0.005287,0.000165,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.845412,0.791842,0.778126,0.809764,0.749410,0.794911,0.032039,37
26,0.227678,0.003615,0.007460,0.000058,absolute_error,log2,25,"{'criterion': 'absolute_error', 'max_features'...",0.847188,0.800236,0.807622,0.822747,0.768421,0.809243,0.025971,19
27,0.445053,0.005453,0.011443,0.001138,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.859976,0.789373,0.812432,0.814583,0.765377,0.808348,0.031393,23
28,0.665572,0.011160,0.015126,0.001151,absolute_error,log2,75,"{'criterion': 'absolute_error', 'max_features'...",0.853495,0.794711,0.812929,0.823230,0.765216,0.809916,0.029376,16
29,0.916605,0.018673,0.020265,0.000513,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.858050,0.790803,0.807261,0.826550,0.777398,0.812012,0.028289,6
30,0.043262,0.000820,0.006208,0.001070,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.831564,0.768490,0.798283,0.827255,0.730286,0.791176,0.037962,38
31,0.097043,0.000834,0.007660,0.000195,poisson,sqrt,25,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.866613,0.758243,0.790460,0.826060,0.774902,0.803256,0.038802,32
32,0.205715,0.007756,0.013077,0.001228,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.856050,0.790934,0.799918,0.832326,0.774814,0.810808,0.029390,13
33,0.290163,0.005734,0.016156,0.000947,poisson,sqrt,75,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.849337,0.786856,0.804244,0.834805,0.768055,0.808659,0.029939,22
34,0.401797,0.006904,0.021088,0.001415,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.860452,0.787203,0.808687,0.831593,0.771530,0.811893,0.031607,8
35,0.045102,0.001720,0.006188,0.000386,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.858295,0.791018,0.782773,0.794471,0.756842,0.796680,0.033508,33
36,0.105564,0.002909,0.008867,0.001138,poisson,log2,25,"{'criterion': 'poisson', 'max_features': 'log2...",0.856860,0.783644,0.806916,0.828331,0.763693,0.807889,0.032736,24
37,0.201816,0.004227,0.012552,0.001183,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.850113,0.784880,0.808367,0.829038,0.765124,0.807504,0.030292,25
38,0.294688,0.003227,0.016202,0.000797,poisson,log2,75,"{'criterion': 'poisson', 'max_features': 'log2...",0.866103,0.792486,0.803421,0.833142,0.772078,0.813446,0.032899,3
39,0.352989,0.015242,0.016546,0.002405,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.859827,0.793051,0.812885,0.828665,0.765623,0.812010,0.031862,7

In [16]:
age=int(input("Enter your age: "))
bmi = float(input("Enter your BMI: "))
children = int(input("Enter number of children: "))
sex = input("Enter your sex (M/F): ")
smoker = input("Are you a smoker? (Y/N): ")
sex_male = 1 if sex == "M" else 0
smoker_yes = 1 if smoker == "Y" else 0

Enter your age:  28
Enter your BMI:  28
Enter number of children:  0
Enter your sex (M/F):  M
Are you a smoker? (Y/N):  Y

In [17]:
Future_Prediction=grid.predict([[age,bmi,children,sex_male,smoker_yes]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[20467.2453808]

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(